### ISSUE TITLE
Car Table extension

### ISSUE THREAD

**Issue by RickyAstle98** [ForzaMods/Forza-Mods-Car-Table#2]
Nevermind

**Comment by szaaamerik** [comment]
The hidden cars can be obtained by the autoshow address, however I will not be moving to that since:

1. its a pain in the ass to find
2. the array of bytes isnt as good

for these reasons the hidden cars will not be available using our tool.

but what do you mean by the messagebox? a thing like: `use at your own risk`?

**Comment by szaaamerik** [comment]
sorry for close ^^ *accident*

**Comment by RickyAstle98** [comment]
Anyway I can understand this is pain to find these cars... Can we have a known ones for fun things? About messagebox - price changed if not use at own risk ;)

**Comment by szaaamerik** [comment]
the messagebox is already included.
